export const ADD_ONE ='ADD_ONE'
export const MINUS_ONE ='MINUS_ONE'
export const ADD_FIVE ='ADD_FIVE'
export const MINUS_FIVE ='MINUS_FIVE'  
export const CHANGE_NAME ='CHANGE_NAME'
export const ADD_PRODUCT = 'ADD_PRODUCT'